package com.hyperlink.companion

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Context
import android.content.Intent
import android.net.wifi.WifiManager
import android.os.IBinder

/**
 * Foreground service with no responsibility beyond existing for as long as the
 * QUIC session is up. Android throttles/drops background apps' UDP traffic
 * (confirmed on-device: keep-alive PINGs kept being generated by quinn every
 * ~3s per its own logs, but stopped reaching the host within ~60-70s of the
 * Activity losing foreground focus, tripping the 10s max_idle_timeout on the
 * host side) — a plain `Activity`-owned connection has no way to opt out of
 * that. `foregroundServiceType="connectedDevice"` is the documented Android
 * exemption for exactly this class of app (a companion device link).
 */
class ConnectionKeepAliveService : Service() {

    companion object {
        private const val CHANNEL_ID = "hyperlink_connection"
        private const val CHANNEL_NAME = "HyperLink Connection"
        private const val NOTIFICATION_ID = 2
        private const val EXTRA_HOST_NAME = "host_name"

        fun start(context: Context, hostName: String) {
            val intent = Intent(context, ConnectionKeepAliveService::class.java).apply {
                putExtra(EXTRA_HOST_NAME, hostName)
            }
            context.startForegroundService(intent)
        }

        fun stop(context: Context) {
            context.stopService(Intent(context, ConnectionKeepAliveService::class.java))
        }
    }

    /**
     * Keeps Wi-Fi out of power-save while linked. In power-save the radio batches
     * packets, which adds delay and bursty loss — fatal for screen mirroring and
     * remote input.
     */
    private var wifiLock: WifiManager.WifiLock? = null

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        createNotificationChannel()
        val wifi = applicationContext.getSystemService(WifiManager::class.java)
        wifiLock = wifi?.createWifiLock(WifiManager.WIFI_MODE_FULL_LOW_LATENCY, "HyperLink:link")?.apply {
            setReferenceCounted(false)
            acquire()
        }
    }

    override fun onDestroy() {
        wifiLock?.takeIf { it.isHeld }?.release()
        wifiLock = null
        super.onDestroy()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        val hostName = intent?.getStringExtra(EXTRA_HOST_NAME) ?: "host"
        startForeground(NOTIFICATION_ID, buildNotification(hostName))
        return START_STICKY
    }

    private fun createNotificationChannel() {
        val channel = NotificationChannel(
            CHANNEL_ID,
            CHANNEL_NAME,
            NotificationManager.IMPORTANCE_LOW
        ).apply {
            description = "Shows while HyperLink is connected to a paired host"
        }
        val manager = getSystemService(NotificationManager::class.java)
        manager.createNotificationChannel(channel)
    }

    private fun buildNotification(hostName: String): Notification {
        return Notification.Builder(this, CHANNEL_ID)
            .setContentTitle("HyperLink Connected")
            .setContentText("Linked to $hostName")
            .setSmallIcon(android.R.drawable.ic_menu_share)
            .setOngoing(true)
            .build()
    }
}
