package com.hyperlink.companion

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.os.IBinder

/**
 * Foreground service that keeps the app process alive while it's linked to a
 * computer, and for a while after an unexpected drop while [Link] reconnects.
 *
 * Android throttles/drops background apps' UDP traffic (confirmed on-device:
 * keep-alive PINGs kept being generated by quinn every ~3s per its own logs,
 * but stopped reaching the host within ~60-70s of the Activity losing
 * foreground focus, tripping the 10s max_idle_timeout on the host side).
 * `foregroundServiceType="connectedDevice"` is the documented Android exemption
 * for exactly this class of app (a companion device link). The notification is
 * also the user's way to see the link and end it without opening the app.
 */
class ConnectionKeepAliveService : Service() {

    companion object {
        private const val CHANNEL_ID = "hyperlink_connection"
        private const val CHANNEL_NAME = "Connection status"
        private const val NOTIFICATION_ID = 2
        private const val EXTRA_HOST_NAME = "host_name"
        private const val EXTRA_RECONNECTING = "reconnecting"
        private const val ACTION_DISCONNECT = "com.hyperlink.companion.DISCONNECT"

        /** Shows "Linked to <computer>" (starting the service if needed). */
        fun showLinked(context: Context, hostName: String) = start(context, hostName, reconnecting = false)

        /** Shows "Reconnecting to <computer>…" while [Link] keeps trying. */
        fun showReconnecting(context: Context, hostName: String) = start(context, hostName, reconnecting = true)

        private fun start(context: Context, hostName: String, reconnecting: Boolean) {
            val intent = Intent(context, ConnectionKeepAliveService::class.java)
                .putExtra(EXTRA_HOST_NAME, hostName)
                .putExtra(EXTRA_RECONNECTING, reconnecting)
            try {
                context.startForegroundService(intent)
            } catch (e: IllegalStateException) {
                // Android may refuse a new foreground service from the background
                // (e.g. if it was never started); the link still works while the
                // app is open, it just can't outlive it this time.
                android.util.Log.w("KeepAlive", "could not start foreground service: ${e.message}")
            }
        }

        fun stop(context: Context) {
            context.stopService(Intent(context, ConnectionKeepAliveService::class.java))
        }
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        createNotificationChannel()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_DISCONNECT) {
            Link.disconnect()
            stopSelf()
            return START_NOT_STICKY
        }
        val hostName = intent?.getStringExtra(EXTRA_HOST_NAME) ?: "your computer"
        val reconnecting = intent?.getBooleanExtra(EXTRA_RECONNECTING, false) ?: false
        startForeground(NOTIFICATION_ID, buildNotification(hostName, reconnecting))
        // Not sticky: after the process dies, the link restarts when the app is
        // opened rather than from a stale service with no connection behind it.
        return START_NOT_STICKY
    }

    private fun createNotificationChannel() {
        val channel = NotificationChannel(
            CHANNEL_ID,
            CHANNEL_NAME,
            NotificationManager.IMPORTANCE_LOW
        ).apply {
            description = "Shows while HyperLink is linked to your computer"
            setShowBadge(false)
        }
        val manager = getSystemService(NotificationManager::class.java)
        manager.createNotificationChannel(channel)
    }

    private fun buildNotification(hostName: String, reconnecting: Boolean): Notification {
        val open = PendingIntent.getActivity(
            this,
            0,
            Intent(this, MainActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP),
            PendingIntent.FLAG_IMMUTABLE,
        )
        val disconnect = PendingIntent.getService(
            this,
            1,
            Intent(this, ConnectionKeepAliveService::class.java).setAction(ACTION_DISCONNECT),
            PendingIntent.FLAG_IMMUTABLE,
        )
        val (title, text) = if (reconnecting) {
            "Reconnecting to $hostName…" to "HyperLink will reconnect when your computer is back on Wi-Fi."
        } else {
            "Linked to $hostName" to "Notifications, clipboard and files are shared with your computer."
        }
        return Notification.Builder(this, CHANNEL_ID)
            .setContentTitle(title)
            .setContentText(text)
            .setSmallIcon(R.drawable.ic_hyperlink_mark)
            .setContentIntent(open)
            .addAction(Notification.Action.Builder(null, "Disconnect", disconnect).build())
            .setOngoing(true)
            .setForegroundServiceBehavior(Notification.FOREGROUND_SERVICE_IMMEDIATE)
            .build()
    }
}
